"""Writes wizard answers to /etc/codered/sensor.conf."""

import configparser
import os
import shutil
from pathlib import Path

CONF_DIR = '/etc/codered'
CONF_FILE = os.path.join(CONF_DIR, 'sensor.conf')
DEFAULTS_FILE = os.path.join(CONF_DIR, 'codered.defaults')
SETUP_SENTINEL = os.path.join(CONF_DIR, '.setup-complete')


def load_defaults() -> configparser.ConfigParser:
    """Load default configuration values."""
    config = configparser.ConfigParser()
    if os.path.exists(DEFAULTS_FILE):
        config.read(DEFAULTS_FILE)
    return config


def write_config(answers: dict) -> str:
    """Write wizard answers to sensor.conf.

    Args:
        answers: dict with keys matching section.option format, e.g.:
            {
                'sensor.hostname': 'my-sensor',
                'network.mgmt_ip': '10.0.0.5',
                ...
            }

    Returns:
        Path to written config file.
    """
    config = load_defaults()

    for key, value in answers.items():
        section, option = key.split('.', 1)
        if not config.has_section(section):
            config.add_section(section)
        config.set(section, option, str(value))

    os.makedirs(CONF_DIR, mode=0o750, exist_ok=True)
    with open(CONF_FILE, 'w') as f:
        f.write("# CodeRed NDR - Instance Configuration\n")
        f.write("# Generated by first-boot wizard. Do not edit manually.\n\n")
        config.write(f)

    os.chmod(CONF_FILE, 0o640)
    return CONF_FILE


def read_config() -> configparser.ConfigParser:
    """Read current sensor configuration."""
    config = load_defaults()
    if os.path.exists(CONF_FILE):
        config.read(CONF_FILE)
    return config


def mark_setup_complete():
    """Create sentinel file indicating setup has been completed."""
    Path(SETUP_SENTINEL).touch(mode=0o644)


def is_setup_complete() -> bool:
    """Check if first-boot setup has already been completed."""
    return os.path.exists(SETUP_SENTINEL)


def get_config_value(section: str, option: str, fallback: str = '') -> str:
    """Get a single configuration value."""
    config = read_config()
    return config.get(section, option, fallback=fallback)
