#!/bin/bash
# ╔══════════════════════════════════════════════════════════════╗
# ║  CodeRed NDR - First Boot Setup Wizard                      ║
# ║  Configures sensor on initial deployment                     ║
# ╚══════════════════════════════════════════════════════════════╝
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

CONF="/etc/codered/sensor.conf"
DEFAULTS="/etc/codered/codered.defaults"
MARKER="/var/lib/codered/.firstboot-complete"

[ "$(id -u)" -eq 0 ] || { echo "Must run as root."; exit 1; }

clear
echo -e "${BOLD}${CYAN}"
echo "  ╔══════════════════════════════════════════════════════════╗"
echo "  ║         CodeRed NDR - First Boot Setup Wizard           ║"
echo "  ╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

# --- Hostname ---
read -rp "  Sensor hostname [codered-sensor]: " INPUT_HOSTNAME
SENSOR_HOSTNAME="${INPUT_HOSTNAME:-codered-sensor}"

# --- Sensor name ---
read -rp "  Sensor name (identifier for SIEM) [sensor-01]: " INPUT_SNAME
SENSOR_NAME="${INPUT_SNAME:-sensor-01}"

# --- List available interfaces ---
echo ""
echo -e "  ${BOLD}Available network interfaces:${NC}"
echo "  ─────────────────────────────────────"
ip -br link show | grep -v lo | while read -r iface state mac rest; do
    ADDR=$(ip -4 addr show "$iface" 2>/dev/null | awk '/inet /{print $2}' | head -1)
    printf "    %-15s  %-8s  %s  %s\n" "$iface" "$state" "$mac" "${ADDR:-no-ip}"
done
echo ""

# --- Management interface ---
DEFAULT_MGMT=$(ip route get 8.8.8.8 2>/dev/null | awk '{for(i=1;i<=NF;i++)if($i=="dev")print $(i+1)}' | head -1)
read -rp "  Management interface [$DEFAULT_MGMT]: " INPUT_MGMT
MGMT_IF="${INPUT_MGMT:-$DEFAULT_MGMT}"

# Validate management interface
if ! ip link show "$MGMT_IF" &>/dev/null; then
    echo -e "  ${RED}[x] Interface $MGMT_IF not found.${NC}"
    exit 1
fi

# --- Management IP config ---
echo ""
echo "  Management IP configuration:"
echo "    [1] DHCP (default)"
echo "    [2] Static IP"
read -rp "  Select [1]: " IP_MODE
IP_MODE="${IP_MODE:-1}"

MGMT_MODE="dhcp"
MGMT_IP=""
MGMT_NETMASK=""
MGMT_GATEWAY=""
MGMT_DNS="8.8.8.8,8.8.4.4"

if [ "$IP_MODE" = "2" ]; then
    MGMT_MODE="static"
    read -rp "  Static IP (CIDR, e.g. 192.168.1.100/24): " MGMT_IP
    read -rp "  Gateway: " MGMT_GATEWAY
    read -rp "  DNS servers [8.8.8.8,8.8.4.4]: " INPUT_DNS
    MGMT_DNS="${INPUT_DNS:-8.8.8.8,8.8.4.4}"
fi

# --- Monitor interface ---
echo ""
read -rp "  Monitor/capture interface (SPAN/TAP port): " MONITOR_IF

if [ -z "$MONITOR_IF" ]; then
    echo -e "  ${YELLOW}[!] No monitor interface set. You can configure this later via CLI.${NC}"
elif ! ip link show "$MONITOR_IF" &>/dev/null; then
    echo -e "  ${RED}[x] Interface $MONITOR_IF not found.${NC}"
    exit 1
fi

# --- SIEM Configuration ---
echo ""
echo -e "  ${BOLD}SIEM Forwarding Configuration:${NC}"
echo "  ─────────────────────────────────────"
echo "    [1] Elasticsearch (default port 9200)"
echo "    [2] Logstash (default port 5044)"
echo "    [3] Syslog / CEF (default port 514)"
echo ""
read -rp "  SIEM output type [1]: " SIEM_TYPE
SIEM_TYPE="${SIEM_TYPE:-1}"

case "$SIEM_TYPE" in
    1) SIEM_OUTPUT="elasticsearch"; DEFAULT_PORT="9200" ;;
    2) SIEM_OUTPUT="logstash"; DEFAULT_PORT="5044" ;;
    3) SIEM_OUTPUT="syslog"; DEFAULT_PORT="514" ;;
    *) SIEM_OUTPUT="elasticsearch"; DEFAULT_PORT="9200" ;;
esac

read -rp "  SIEM address (IP or FQDN): " SIEM_HOST
if [ -z "$SIEM_HOST" ]; then
    echo -e "  ${YELLOW}[!] No SIEM address set. Configure later via CLI.${NC}"
    SIEM_HOST="__SIEM_HOST__"
    SIEM_PORT="$DEFAULT_PORT"
else
    read -rp "  SIEM port [$DEFAULT_PORT]: " INPUT_PORT
    SIEM_PORT="${INPUT_PORT:-$DEFAULT_PORT}"
fi

# TLS
SIEM_TLS="false"
if [ "$SIEM_HOST" != "__SIEM_HOST__" ]; then
    read -rp "  Use TLS for SIEM connection? (y/N): " TLS_INPUT
    if [[ "$TLS_INPUT" =~ ^[Yy]$ ]]; then
        SIEM_TLS="true"
    fi
fi

# --- Summary ---
echo ""
echo -e "  ${BOLD}Configuration Summary:${NC}"
echo "  ─────────────────────────────────────"
echo "  Hostname:           $SENSOR_HOSTNAME"
echo "  Sensor Name:        $SENSOR_NAME"
echo "  Management IF:      $MGMT_IF ($MGMT_MODE)"
[ "$MGMT_MODE" = "static" ] && echo "  Management IP:      $MGMT_IP"
echo "  Monitor IF:         ${MONITOR_IF:-not set}"
echo "  SIEM Output:        $SIEM_OUTPUT"
echo "  SIEM Destination:   $SIEM_HOST:$SIEM_PORT"
echo "  TLS:                $SIEM_TLS"
echo ""
read -rp "  Apply this configuration? (Y/n): " CONFIRM
if [[ "$CONFIRM" =~ ^[Nn]$ ]]; then
    echo "  Cancelled."
    exit 0
fi

# --- Apply Configuration ---
echo ""
echo -e "  ${GREEN}Applying configuration...${NC}"

# Write sensor.conf
cat > "$CONF" << SENSORCONF
# CodeRed NDR - Sensor Configuration
# Generated by first-boot wizard on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

[sensor]
hostname = $SENSOR_HOSTNAME
sensor_name = $SENSOR_NAME

[network]
mgmt_interface = $MGMT_IF
mgmt_mode = $MGMT_MODE
mgmt_ip = $MGMT_IP
mgmt_gateway = $MGMT_GATEWAY
mgmt_dns = $MGMT_DNS
monitor_interface = ${MONITOR_IF:-}

[forwarding]
siem_output = $SIEM_OUTPUT
siem_host = $SIEM_HOST
siem_port = $SIEM_PORT
siem_tls = $SIEM_TLS
SENSORCONF
chmod 640 "$CONF"

# Set hostname
hostnamectl set-hostname "$SENSOR_HOSTNAME" 2>/dev/null || \
    echo "$SENSOR_HOSTNAME" > /etc/hostname

# Generate unique digest salt for Zeek
ZEEK_SALT=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)
sed -i "s|codered-ndr-changeme-at-firstboot|${ZEEK_SALT}|" /opt/zeek/share/zeek/site/local.zeek

# Update Zeek node.cfg with monitor interface
if [ -n "${MONITOR_IF:-}" ]; then
    sed -i "s|interface=.*|interface=af_packet::${MONITOR_IF}|" /opt/zeek/etc/node.cfg

    # Tune the capture interface
    /opt/codered/bin/tune-interface.sh "$MONITOR_IF" 2>/dev/null || true
fi

# Configure Filebeat output
FILEBEAT_CFG="/etc/filebeat/filebeat.yml"

# Disable all outputs first
sed -i 's/^output\.elasticsearch:/output.elasticsearch:/' "$FILEBEAT_CFG"
sed -i 's/^output\.logstash:/output.logstash:/' "$FILEBEAT_CFG"

case "$SIEM_OUTPUT" in
    elasticsearch)
        sed -i "s|__SIEM_HOST__|${SIEM_HOST}|g" "$FILEBEAT_CFG"
        sed -i "s|__SIEM_PORT__|${SIEM_PORT}|g" "$FILEBEAT_CFG"
        # Enable elasticsearch output, disable logstash
        python3 -c "
import re
with open('$FILEBEAT_CFG', 'r') as f:
    content = f.read()
# Enable elasticsearch
content = re.sub(r'(output\.elasticsearch:\n\s+enabled: )false', r'\1true', content)
# Ensure logstash stays disabled
content = re.sub(r'(output\.logstash:\n\s+enabled: )true', r'\1false', content)
# Set TLS
if '$SIEM_TLS' == 'true':
    content = content.replace('protocol: \"https\"', 'protocol: \"https\"')
    content = content.replace('ssl.verification_mode: \"none\"', 'ssl.verification_mode: \"none\"')
else:
    content = content.replace('protocol: \"https\"', 'protocol: \"http\"')
with open('$FILEBEAT_CFG', 'w') as f:
    f.write(content)
"
        ;;
    logstash)
        sed -i "s|__SIEM_HOST__|${SIEM_HOST}|g" "$FILEBEAT_CFG"
        sed -i "s|__SIEM_PORT__|${SIEM_PORT}|g" "$FILEBEAT_CFG"
        python3 -c "
import re
with open('$FILEBEAT_CFG', 'r') as f:
    content = f.read()
content = re.sub(r'(output\.elasticsearch:\n\s+enabled: )true', r'\1false', content)
content = re.sub(r'(output\.logstash:\n\s+enabled: )false', r'\1true', content)
if '$SIEM_TLS' == 'true':
    content = content.replace('ssl.enabled: false', 'ssl.enabled: true')
with open('$FILEBEAT_CFG', 'w') as f:
    f.write(content)
"
        ;;
    syslog)
        # For syslog output, replace the logstash section with syslog
        python3 -c "
import re
with open('$FILEBEAT_CFG', 'r') as f:
    content = f.read()
content = re.sub(r'(output\.elasticsearch:\n\s+enabled: )true', r'\1false', content)
content = re.sub(r'(output\.logstash:\n\s+enabled: )true', r'\1false', content)
# Append syslog output
syslog_cfg = '''
output.syslog:
  enabled: true
  address: \"$SIEM_HOST:$SIEM_PORT\"
  network: \"tcp\"
  format: \"rfc5424\"
'''
content += syslog_cfg
with open('$FILEBEAT_CFG', 'w') as f:
    f.write(content)
"
        ;;
esac

# Set sensor name in Filebeat
sed -i "s|\${SENSOR_NAME:codered-sensor}|\${SENSOR_NAME:${SENSOR_NAME}}|g" "$FILEBEAT_CFG"

# Configure static IP if selected
if [ "$MGMT_MODE" = "static" ] && [ -n "$MGMT_IP" ]; then
    # Use netplan (Ubuntu 24.04 standard)
    NETPLAN_FILE="/etc/netplan/01-codered-mgmt.yaml"
    cat > "$NETPLAN_FILE" << NETPLAN
network:
  version: 2
  ethernets:
    ${MGMT_IF}:
      addresses:
        - ${MGMT_IP}
      routes:
        - to: default
          via: ${MGMT_GATEWAY}
      nameservers:
        addresses: [$(echo "$MGMT_DNS" | tr ',' ', ')]
NETPLAN
    chmod 600 "$NETPLAN_FILE"
    netplan apply 2>/dev/null || warn "Netplan apply failed — check config manually"
fi

# Mark first boot as complete
touch "$MARKER"
echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > "$MARKER"

echo ""
echo -e "  ${GREEN}${BOLD}Configuration applied successfully!${NC}"
echo ""
echo "  Next steps:"
echo "    1. Start NDR services:  sudo coderedndr  → option 9"
echo "    2. Verify logs flowing:  sudo coderedndr  → option 3"
echo ""
